use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Usage Monitor",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    models: "Models",
    claude_code_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Settings",
    start_with_windows: "Start with Windows",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    theme: "Theme",
    theme_dark: "Dark",
    theme_light: "Light",
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    exit: "Exit",
    show_widget: "Show Widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Claude Code Auth Error",
    token_expired_body: "Run 'claude' in a terminal, then use '/login' and follow the prompts. After that, refresh or restart this app.",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    antigravity_token_expired_title: "Antigravity Auth Error",
    antigravity_token_expired_body: "Open Antigravity and sign in again. After that, refresh or restart this app.",
    codex_window_title: "Codex Usage Monitor",
    antigravity_window_title: "Antigravity Usage Monitor",
    second_suffix: "s",
    pace_colors: "Colour by pace",
    scoped_weekly_row: "Per-model weekly row",
    detailed_time: "Detailed time (hours and minutes)",
    auto_install_updates: "Install updates automatically",
    usage_title: "Usage",
    updated_at: "Updated {time}",
    limit_projection: "Limit in ~{time} at this pace",
    bug_legend: "Where the clock says you should be",
    no_data: "No data",
    sign_in_again: "Sign in again",
};
