use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量監控",
    refresh: "重新整理",
    update_frequency: "更新頻率",
    one_minute: "1 分鐘",
    five_minutes: "5 分鐘",
    fifteen_minutes: "15 分鐘",
    one_hour: "1 小時",
    models: "模型",
    claude_code_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "開機時啟動",
    reset_position: "重置位置",
    language: "語言",
    system_default: "系統預設",
    theme: "主題",
    theme_dark: "深色",
    theme_light: "淺色",
    check_for_updates: "檢查更新",
    checking_for_updates: "正在檢查更新...",
    updates: "更新",
    update_in_progress: "已有更新檢查正在進行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "無法自動更新",
    applying_update: "正在套用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "結束",
    show_widget: "顯示小工具",
    session_window: "5h",
    weekly_window: "7d",
    now: "現在",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    token_expired_title: "驗證錯誤",
    token_expired_body: "請在終端機中執行 'claude'，然後使用 '/login' 並依照提示操作。完成後，請重新整理或重新啟動此應用程式。",
    codex_token_expired_title: "Codex 驗證錯誤",
    codex_token_expired_body: "請在終端機中執行 'codex'，並依照登入提示操作。完成後，請重新整理或重新啟動此應用程式。",
    antigravity_token_expired_title: "Antigravity 驗證錯誤",
    antigravity_token_expired_body: "請開啟 Antigravity 並重新登入。完成後，請重新整理或重新啟動此應用程式。",
    codex_window_title: "Codex 使用量監控",
    antigravity_window_title: "Antigravity 使用量監控",
    second_suffix: "秒",
    pace_colors: "依消耗速度著色",
    scoped_weekly_row: "各模型週用量列",
    detailed_time: "詳細時間 (時與分)",
    auto_install_updates: "自動安裝更新",
    usage_title: "用量",
    updated_at: "更新於 {time}",
    limit_projection: "照此速度約 {time} 後達到上限",
    bug_legend: "依時間應在的位置",
    no_data: "無資料",
    sign_in_again: "請重新登入",
};
