use std::time::{SystemTime, UNIX_EPOCH};

use windows::core::PCWSTR;
use windows::Win32::Foundation::{BOOL, FILETIME, HWND, LPARAM, RECT, SYSTEMTIME, WPARAM};
use windows::Win32::Globalization::{
    GetDateFormatEx, GetTimeFormatEx, DATE_SHORTDATE, TIME_NOSECONDS,
};
use windows::Win32::System::Time::{FileTimeToSystemTime, SystemTimeToTzSpecificLocalTime};
use windows::Win32::Graphics::Gdi::{
    GetMonitorInfoW, MonitorFromWindow, MONITORINFO, MONITORINFOEXW, MONITOR_DEFAULTTONULL,
};
use windows::Win32::UI::Accessibility::{SetWinEventHook, UnhookWinEvent, HWINEVENTHOOK};
use windows::Win32::UI::Controls::{
    InitCommonControlsEx, ICC_WIN95_CLASSES, INITCOMMONCONTROLSEX, TOOLTIPS_CLASS, TTF_IDISHWND, TTF_SUBCLASS, TTM_ADDTOOLW, TTM_SETMAXTIPWIDTH,
    TTM_UPDATETIPTEXTW, TTS_ALWAYSTIP, TTS_NOPREFIX, TTTOOLINFOW,
};
use windows::Win32::UI::Shell::{SHAppBarMessage, ABM_GETTASKBARPOS, APPBARDATA};
use windows::Win32::UI::WindowsAndMessaging::*;

// Window style constants
pub const WS_POPUP_STYLE: u32 = 0x80000000;
pub const WS_CHILD_STYLE: u32 = 0x40000000;
pub const WS_CLIPSIBLINGS_STYLE: u32 = 0x04000000;

/// `MONITORINFOF_PRIMARY`: a plain Win32 define, not generated by the crate.
const MONITOR_FLAG_PRIMARY: u32 = 1;

// Win event constants
pub const EVENT_OBJECT_LOCATIONCHANGE: u32 = 0x800B;
pub const WINEVENT_OUTOFCONTEXT: u32 = 0x0000;

// Timer IDs
pub const TIMER_POLL: usize = 1;
pub const TIMER_COUNTDOWN: usize = 2;
pub const TIMER_RESET_POLL: usize = 3;
pub const TIMER_UPDATE_CHECK: usize = 4;

// Custom messages
pub const WM_APP: u32 = 0x8000;
pub const WM_APP_USAGE_UPDATED: u32 = WM_APP + 1;
pub const WM_APP_TRAY: u32 = WM_APP + 3;

#[derive(Clone, Debug)]
pub struct TaskbarWindow {
    pub hwnd: HWND,
    pub rect: RECT,
    /// Display device name of the monitor this taskbar sits on, e.g.
    /// `\\.\DISPLAY1`. Survives taskbar rebuilds, unlike a position in the
    /// enumeration or a window handle.
    pub device: Option<String>,
    /// Whether this taskbar sits on the primary monitor.
    pub is_primary: bool,
}

/// Display device name of the monitor a window is on, and whether that monitor
/// is the primary one.
pub fn monitor_of_window(hwnd: HWND) -> Option<(String, bool)> {
    unsafe {
        // DEFAULTTONULL, not DEFAULTTONEAREST: a window the shell has created but
        // not yet positioned sits at (0,0,0,0), and "nearest" would confidently
        // attribute it to the primary monitor. Better to report nothing.
        let monitor = MonitorFromWindow(hwnd, MONITOR_DEFAULTTONULL);
        if monitor.is_invalid() {
            return None;
        }

        let mut info = MONITORINFOEXW::default();
        info.monitorInfo.cbSize = std::mem::size_of::<MONITORINFOEXW>() as u32;
        let ok = GetMonitorInfoW(monitor, &mut info as *mut MONITORINFOEXW as *mut MONITORINFO);
        if !ok.as_bool() {
            return None;
        }

        let len = info
            .szDevice
            .iter()
            .position(|&c| c == 0)
            .unwrap_or(info.szDevice.len());
        if len == 0 {
            return None;
        }

        Some((
            String::from_utf16_lossy(&info.szDevice[..len]),
            info.monitorInfo.dwFlags & MONITOR_FLAG_PRIMARY != 0,
        ))
    }
}

pub fn find_taskbars() -> Vec<TaskbarWindow> {
    unsafe extern "system" fn enum_proc(hwnd: HWND, lparam: LPARAM) -> BOOL {
        let taskbars = &mut *(lparam.0 as *mut Vec<TaskbarWindow>);
        let mut class_name = [0u16; 64];
        let len = unsafe { GetClassNameW(hwnd, &mut class_name) };
        if len > 0 {
            let class_name = String::from_utf16_lossy(&class_name[..len as usize]);
            if class_name == "Shell_TrayWnd" || class_name == "Shell_SecondaryTrayWnd" {
                if let Some(rect) = get_taskbar_rect(hwnd).or_else(|| get_window_rect_safe(hwnd)) {
                    if rect.right <= rect.left || rect.bottom <= rect.top {
                        // Mid-creation, before the shell has positioned it. Its
                        // geometry would sort ahead of every real taskbar.
                        return BOOL(1);
                    }
                    let monitor = monitor_of_window(hwnd);
                    taskbars.push(TaskbarWindow {
                        hwnd,
                        rect,
                        device: monitor.as_ref().map(|(device, _)| device.clone()),
                        is_primary: monitor.map(|(_, primary)| primary).unwrap_or(false),
                    });
                }
            }
        }
        BOOL(1)
    }

    let mut taskbars: Vec<TaskbarWindow> = Vec::new();
    unsafe {
        let _ = EnumWindows(Some(enum_proc), LPARAM(&mut taskbars as *mut _ as isize));
    }
    taskbars.sort_by_key(|taskbar| {
        (
            taskbar.rect.top,
            taskbar.rect.left,
            taskbar.rect.bottom,
            taskbar.rect.right,
        )
    });
    taskbars
}

/// Find a child window by class name
pub fn find_child_window(parent: HWND, class_name: &str) -> Option<HWND> {
    unsafe {
        let class = wide_str(class_name);
        match FindWindowExW(
            parent,
            HWND::default(),
            PCWSTR::from_raw(class.as_ptr()),
            PCWSTR::null(),
        ) {
            Ok(h) if h != HWND::default() => Some(h),
            _ => None,
        }
    }
}

/// Get taskbar position via SHAppBarMessage
pub fn get_taskbar_rect(taskbar_hwnd: HWND) -> Option<RECT> {
    unsafe {
        let mut class_name = [0u16; 64];
        let len = GetClassNameW(taskbar_hwnd, &mut class_name);
        if len > 0 {
            let class_name = String::from_utf16_lossy(&class_name[..len as usize]);
            if class_name == "Shell_SecondaryTrayWnd" {
                return get_window_rect_safe(taskbar_hwnd);
            }
        }

        let mut abd = APPBARDATA {
            cbSize: std::mem::size_of::<APPBARDATA>() as u32,
            hWnd: taskbar_hwnd,
            ..Default::default()
        };
        let result = SHAppBarMessage(ABM_GETTASKBARPOS, &mut abd);
        if result == 0 {
            return None;
        }
        Some(abd.rc)
    }
}

/// Get the bounding rectangle of a window
pub fn get_window_rect_safe(hwnd: HWND) -> Option<RECT> {
    unsafe {
        let mut rect = RECT::default();
        if GetWindowRect(hwnd, &mut rect).is_ok() {
            Some(rect)
        } else {
            None
        }
    }
}

/// Embed our window as a child of the taskbar
pub fn embed_in_taskbar(hwnd: HWND, taskbar_hwnd: HWND) {
    unsafe {
        // Preserve existing extended style, add tool window + no activate
        let ex_style = GetWindowLongW(hwnd, GWL_EXSTYLE);
        let _ = SetWindowLongW(
            hwnd,
            GWL_EXSTYLE,
            ex_style | WS_EX_TOOLWINDOW.0 as i32 | WS_EX_NOACTIVATE.0 as i32,
        );

        // Change from popup to child
        let style = GetWindowLongW(hwnd, GWL_STYLE) as u32;
        let new_style = (style & !WS_POPUP_STYLE) | WS_CHILD_STYLE | WS_CLIPSIBLINGS_STYLE;
        let _ = SetWindowLongW(hwnd, GWL_STYLE, new_style as i32);

        let _ = SetParent(hwnd, taskbar_hwnd);
    }
}

/// Move the window
pub fn move_window(hwnd: HWND, x: i32, y: i32, w: i32, h: i32) {
    unsafe {
        let _ = MoveWindow(hwnd, x, y, w, h, true);
    }
}

/// Set up a WinEvent hook for tray location changes
pub fn set_tray_event_hook(
    thread_id: u32,
    callback: unsafe extern "system" fn(HWINEVENTHOOK, u32, HWND, i32, i32, u32, u32),
) -> Option<HWINEVENTHOOK> {
    unsafe {
        let hook = SetWinEventHook(
            EVENT_OBJECT_LOCATIONCHANGE,
            EVENT_OBJECT_LOCATIONCHANGE,
            None,
            Some(callback),
            0,
            thread_id,
            WINEVENT_OUTOFCONTEXT,
        );
        if hook.is_invalid() {
            None
        } else {
            Some(hook)
        }
    }
}

/// Get the thread ID that owns a window
pub fn get_window_thread_id(hwnd: HWND) -> u32 {
    unsafe { GetWindowThreadProcessId(hwnd, None) }
}

/// Unhook a WinEvent hook
pub fn unhook_win_event(hook: HWINEVENTHOOK) {
    unsafe {
        let _ = UnhookWinEvent(hook);
    }
}

/// Convert a Rust string to a null-terminated wide string
pub fn wide_str(s: &str) -> Vec<u16> {
    s.encode_utf16().chain(std::iter::once(0)).collect()
}

/// COLORREF wrapper (RGB packed into u32)
pub fn colorref(r: u8, g: u8, b: u8) -> u32 {
    r as u32 | (g as u32) << 8 | (b as u32) << 16
}

/// Color helper
#[derive(Clone, Copy, Debug)]
pub struct Color {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

impl Color {
    #[allow(dead_code)]
    pub const fn new(r: u8, g: u8, b: u8) -> Self {
        Self { r, g, b }
    }

    pub fn from_hex(hex: &str) -> Self {
        let hex = hex.trim_start_matches('#');
        let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(0);
        let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(0);
        let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(0);
        Self { r, g, b }
    }

    /// Parse a colour that came from the settings file, where anything at all
    /// may be written. `from_hex` indexes blindly and would panic.
    pub fn try_from_hex(hex: &str) -> Option<Self> {
        let hex = hex.trim().trim_start_matches('#');
        if hex.len() != 6 || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
            return None;
        }

        Some(Self {
            r: u8::from_str_radix(&hex[0..2], 16).ok()?,
            g: u8::from_str_radix(&hex[2..4], 16).ok()?,
            b: u8::from_str_radix(&hex[4..6], 16).ok()?,
        })
    }

    pub fn to_colorref(self) -> u32 {
        colorref(self.r, self.g, self.b)
    }
}

/// 100-nanosecond intervals between 1601-01-01 (the FILETIME epoch) and
/// 1970-01-01 (the Unix epoch).
const FILETIME_TO_UNIX_EPOCH_TICKS: u64 = 116_444_736_000_000_000;

fn unix_seconds_to_filetime_ticks(seconds: u64) -> Option<u64> {
    seconds
        .checked_mul(10_000_000)?
        .checked_add(FILETIME_TO_UNIX_EPOCH_TICKS)
}

/// Convert an instant into the local wall-clock time Windows would show for it.
fn to_local_systemtime(time: SystemTime) -> Option<SYSTEMTIME> {
    let seconds = time.duration_since(UNIX_EPOCH).ok()?.as_secs();
    let ticks = unix_seconds_to_filetime_ticks(seconds)?;

    let utc = FILETIME {
        dwLowDateTime: ticks as u32,
        dwHighDateTime: (ticks >> 32) as u32,
    };

    unsafe {
        let mut universal = SYSTEMTIME::default();
        FileTimeToSystemTime(&utc, &mut universal).ok()?;
        // Converting through the time zone rather than shifting the FILETIME
        // applies the DST offset in force on that date, not today's.
        let mut parts = SYSTEMTIME::default();
        SystemTimeToTzSpecificLocalTime(None, &universal, &mut parts).ok()?;
        Some(parts)
    }
}

fn format_with(
    parts: &SYSTEMTIME,
    formatter: unsafe fn(&SYSTEMTIME, &mut [u16]) -> i32,
) -> Option<String> {
    let mut buffer = [0u16; 128];
    let written = unsafe { formatter(parts, &mut buffer) };
    if written <= 1 {
        return None;
    }
    Some(String::from_utf16_lossy(&buffer[..(written as usize - 1)]))
}

/// Wall-clock time in the user's regional format, so a 12-hour locale gets
/// "5:19 PM" and a 24-hour one "17:19" without us choosing.
pub fn format_local_time(time: SystemTime) -> Option<String> {
    let parts = to_local_systemtime(time)?;
    let same_day = to_local_systemtime(SystemTime::now())
        .map(|now| {
            now.wYear == parts.wYear && now.wMonth == parts.wMonth && now.wDay == parts.wDay
        })
        .unwrap_or(false);

    let clock = format_with(&parts, |parts, buffer| unsafe {
        GetTimeFormatEx(PCWSTR::null(), TIME_NOSECONDS, Some(parts), PCWSTR::null(), Some(buffer))
    })?;

    if same_day {
        return Some(clock);
    }

    let date = format_with(&parts, |parts, buffer| unsafe {
        GetDateFormatEx(
            PCWSTR::null(),
            DATE_SHORTDATE,
            Some(parts),
            PCWSTR::null(),
            Some(buffer),
            PCWSTR::null(),
        )
    })?;
    Some(format!("{date} {clock}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_unix_epoch_sits_at_the_documented_filetime_offset() {
        assert_eq!(
            unix_seconds_to_filetime_ticks(0),
            Some(FILETIME_TO_UNIX_EPOCH_TICKS)
        );
        assert_eq!(
            unix_seconds_to_filetime_ticks(1),
            Some(FILETIME_TO_UNIX_EPOCH_TICKS + 10_000_000)
        );
    }

    #[test]
    fn an_absurd_timestamp_returns_none_instead_of_overflowing() {
        assert_eq!(unix_seconds_to_filetime_ticks(u64::MAX), None);
    }

    #[test]
    fn a_hex_colour_from_the_settings_file_is_parsed_or_refused() {
        assert!(Color::try_from_hex("#3F9142").is_some());
        assert!(Color::try_from_hex("3F9142").is_some());
        assert!(Color::try_from_hex("#3F914").is_none());
        assert!(Color::try_from_hex("#GGGGGG").is_none());
        assert!(Color::try_from_hex("").is_none());
    }
}

/// comctl32 validates `cbSize` against the exact struct version it knows. Without
/// a v6 manifest we talk to v5, which predates `lpReserved` and rejects the full
/// size outright.
fn tool_info_size() -> u32 {
    (std::mem::size_of::<TTTOOLINFOW>() - std::mem::size_of::<*mut std::ffi::c_void>()) as u32
}

fn tool_info(parent: HWND, text: &mut [u16]) -> TTTOOLINFOW {
    TTTOOLINFOW {
        cbSize: tool_info_size(),
        uFlags: TTF_IDISHWND | TTF_SUBCLASS,
        hwnd: parent,
        uId: parent.0 as usize,
        lpszText: windows::core::PWSTR::from_raw(text.as_mut_ptr()),
        ..Default::default()
    }
}

/// The tooltip window class only exists once the common controls are loaded,
/// and this app ships no manifest that would do it for us.
fn ensure_common_controls() -> bool {
    unsafe {
        let init = INITCOMMONCONTROLSEX {
            dwSize: std::mem::size_of::<INITCOMMONCONTROLSEX>() as u32,
            dwICC: ICC_WIN95_CLASSES,
        };
        InitCommonControlsEx(&init).as_bool()
    }
}

/// Attach a standard tooltip to `parent`. `TTF_SUBCLASS` lets the control pick
/// up the hover itself, so the widget keeps its own mouse handling untouched.
pub fn create_tooltip(parent: HWND, text: &mut [u16]) -> Option<TooltipOutcome> {
    if !ensure_common_controls() {
        return Some(TooltipOutcome::CommonControlsFailed);
    }

    unsafe {
        // The owner is deliberately None: our widget is a child of another
        // process's taskbar, and a popup owned by a child window is rejected.
        // Topmost is explicit: an unowned window inherits nothing, and the
        // taskbar it has to appear over is itself topmost.
        let tooltip = match CreateWindowExW(
            WS_EX_TOPMOST,
            TOOLTIPS_CLASS,
            PCWSTR::null(),
            WINDOW_STYLE(WS_POPUP_STYLE | TTS_ALWAYSTIP | TTS_NOPREFIX),
            0,
            0,
            0,
            0,
            None,
            None,
            None,
            None,
        ) {
            Ok(tooltip) => tooltip,
            Err(error) => return Some(TooltipOutcome::CreateFailed(error.code().0 as u32)),
        };

        let mut info = tool_info(parent, text);
        let added = SendMessageW(
            tooltip,
            TTM_ADDTOOLW,
            WPARAM(0),
            LPARAM(&mut info as *mut TTTOOLINFOW as isize),
        );
        if added.0 == 0 {
            let _ = DestroyWindow(tooltip);
            return Some(TooltipOutcome::AddToolFailed);
        }

        // Without a max width the control ignores newlines and renders one line.
        SendMessageW(tooltip, TTM_SETMAXTIPWIDTH, WPARAM(0), LPARAM(400));
        Some(TooltipOutcome::Created(tooltip))
    }
}

/// Why the tooltip could not be attached, so a failure is diagnosable instead
/// of silently absent.
#[derive(Debug)]
pub enum TooltipOutcome {
    Created(HWND),
    CommonControlsFailed,
    CreateFailed(u32),
    AddToolFailed,
}

/// `text` must outlive the tooltip: the control keeps the pointer rather than
/// copying. Callers keep the buffer in app state and only swap it from the UI
/// thread, which is also the only thread the control reads it on.
pub fn set_tooltip_text(tooltip: HWND, parent: HWND, text: &mut [u16]) {
    unsafe {
        let mut info = tool_info(parent, text);
        SendMessageW(
            tooltip,
            TTM_UPDATETIPTEXTW,
            WPARAM(0),
            LPARAM(&mut info as *mut TTTOOLINFOW as isize),
        );
    }
}
